/*
 * #%L
 * ImgLib2: a general-purpose, multidimensional image processing library.
 * %%
 * Copyright (C) 2009 - 2016 Tobias Pietzsch, Stephan Preibisch, Stephan Saalfeld,
 * John Bogovic, Albert Cardona, Barry DeZonia, Christian Dietz, Jan Funke,
 * Aivar Grislis, Jonathan Hale, Grant Harris, Stefan Helfrich, Mark Hiner,
 * Martin Horn, Steffen Jaensch, Lee Kamentsky, Larry Lindsey, Melissa Linkert,
 * Mark Longair, Brian Northan, Nick Perry, Curtis Rueden, Johannes Schindelin,
 * Jean-Yves Tinevez and Michael Zinsmaier.
 * %%
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */

package net.imglib2.realtransform;

import net.imglib2.AbstractEuclideanSpace;
import net.imglib2.Interval;
import net.imglib2.Localizable;
import net.imglib2.Point;
import net.imglib2.RandomAccess;
import net.imglib2.RandomAccessible;
import net.imglib2.RealInterval;
import net.imglib2.transform.Transform;
import net.imglib2.view.TransformedRandomAccessible;

/**
 * A {@link RandomAccessible} whose samples are generated by a
 * {@link RandomAccessible} transformed by an {@link LongAffineTransform
 * integer affine transformation}.  Changing the {@link LongAffineTransform
 * integer affine transformation} will affect the {@link
 * LongAffineRandomAccessible} but not any existing {@link RandomAccess} on it
 * because each {@link RandomAccess} internally works with a copy of the
 * transformation.  Make sure that you request a new {@link RandomAccess} after
 * modifying the transformation.
 *
 * @author Stephan Saalfeld
 */
public class LongAffineRandomAccessible< T > extends AbstractEuclideanSpace implements TransformedRandomAccessible< T >
{
	private final RandomAccessible< T > source;

	private final LongAffineTransform transformToSource;

	/**
	 * {@link RandomAccess} that generates its samples from a source
	 * {@link RandomAccessible} at coordinates transformed by a
	 * {@link Transform}.
	 *
	 */
	public class LongAffineRandomAccess extends Point implements RandomAccess< T >
	{
		/**
		 * source RandomAccess. note that this is the <em>target</em> of the
		 * transformToSource.
		 */
		private final RandomAccess< T > sourceAccess;

		private final LongAffineTransform transformCopy;

		private final long[] tmp = new long[ n ];

		protected LongAffineRandomAccess()
		{
			super( transformToSource.numSourceDimensions() );
			sourceAccess = source.randomAccess();
			transformCopy = transformToSource.copy();
			apply();
		}

		protected LongAffineRandomAccess( final LongAffineRandomAccess access )
		{
			super( transformToSource.numSourceDimensions() );
			access.localize( position );
			sourceAccess = access.sourceAccess.copyRandomAccess();
			transformCopy = transformToSource.copy();
		}

		protected void scaleMove( final long distance, final int d )
		{
			final Localizable dd = transformCopy.d( d );
			for ( int ddd = 0; ddd < n; ++ddd )
				tmp[ ddd ] = distance * dd.getLongPosition( ddd );
		}

		@Override
		public void fwd( final int d )
		{
			super.fwd( d );
			sourceAccess.move( transformCopy.d( d ) );
		}

		@Override
		public void bck( final int d )
		{
			super.bck( d );

			/* TODO storing an inverse of all ds would potentially improve the
			 * performance of bck calls for some overhead on construction of
			 * the access.
			 */
			scaleMove( -1, d );
			sourceAccess.move( tmp );
		}

		@Override
		public void move( final long distance, final int d )
		{
			super.move( distance, d );
			scaleMove( distance, d );
			sourceAccess.move( tmp );
		}

		@Override
		public void move( final int distance, final int d )
		{
			move( ( long ) distance, d );
		}

		@Override
		public void move( final Localizable localizable )
		{
			super.move( localizable );
			apply();
		}

		@Override
		public void move( final int[] distance )
		{
			super.move( distance );
			apply();
		}

		@Override
		public void move( final long[] distance )
		{
			super.move( distance );
			apply();
		}

		@Override
		public void setPosition( final int[] pos )
		{
			super.setPosition( position );
			apply();
		}

		@Override
		public void setPosition( final long[] pos )
		{
			super.setPosition( pos );
			apply();
		}

		@Override
		public void setPosition( final int position, final int d )
		{
			setPosition( ( long ) position, d );
		}

		@Override
		public void setPosition( final long pos, final int d )
		{
			final long distance = pos - position[ d ];
			move( distance, d );
		}

		@Override
		public void setPosition( final Localizable localizable )
		{
			super.setPosition( localizable );
			apply();
		}

		final protected void apply()
		{
			transformCopy.apply( this, sourceAccess );
		}

		@Override
		public T get()
		{
			return sourceAccess.get();
		}

		@Override
		public LongAffineRandomAccess copy()
		{
			return new LongAffineRandomAccess( this );
		}

		@Override
		public LongAffineRandomAccess copyRandomAccess()
		{
			return copy();
		}
	}

	public LongAffineRandomAccessible( final RandomAccessible< T > source, final LongAffineTransform transformToSource )
	{
		super( source.numDimensions() );
		this.source = source;
		this.transformToSource = transformToSource;
	}

	@Override
	public LongAffineRandomAccess randomAccess()
	{
		return new LongAffineRandomAccess();
	}

	/**
	 * To be overridden for {@link RealTransform} that can estimate the
	 * boundaries of a transferred {@link RealInterval}.
	 */
	@Override
	public LongAffineRandomAccess randomAccess( final Interval interval )
	{
		return randomAccess();
	}

	@Override
	public RandomAccessible< T > getSource()
	{
		return source;
	}

	@Override
	public Transform getTransformToSource()
	{
		return transformToSource;
	}
}
